#pragma once

// =============================================================================
// GENERATED SAVED-CONFIG NOTIFICATION HELPERS - do not edit by hand
// Generated by scripts/build.py from product/v2/card_contract.json.
// =============================================================================

template<typename Config, typename OptionHook>
inline bool normalize_saved_config_notification(Config &config,
                                                OptionHook normalize_options) {
  if (config.type != "notification") return false;
    config.icon = "Auto";
    config.icon_on = "Auto";
    config.sensor.clear();
    config.unit.clear();
    config.type = "notification";
    config.precision.clear();
  config.options = normalize_options(config.options, config);
  return true;
}
